Tatlin
======

Tatlin is a Gcode and STL viewer heavily inspired by Mac-only software
Pleasant3D. Besides viewing, it also supports rotating and scaling of STL
files. It is currently in early stages of development, but should already
be quite usable.

Dependencies
------------

Tatlin requires the following packages:

- Python 2.6+
- PyGTK 2.24
- PyOpenGL
- Python bindings for GtkGLExt
- NumPy

Usage
-----

To launch Tatlin from the command line:

    $ ./tatlin [--hide-panel]

You can also provide a filename to load:

    $ ./tatlin [--hide-panel] foobar.stl

Mouse navigation

* Left mouse button to rotate
* Mouse wheel to zoom
* Middle mouse button to offset the platform
* Right mouse button to pan

Build platform size can be customized by creating a file called `.tatlin` in
your home directory with the following contents:

    [machine]
    platform_w = 300
    platform_d = 300

Thanks
------

* Lenbok for config file options
* Bartosz Zaborowski for the two digit Gcode patch

Remark
------

This is a friendly fork of the original tatlin application by Denis Kobozev
(https://github.com/dkobozev/tatlin) with a few additional quirks, to make it
fit more perfectly to my primary use.

As I don't really like the GUI of OpenSCAD (especially I'm missing a few 
features in the built-in source code editor), I switched to edit the source 
in gEdit and use OpenSCAD on the command line to export STL files. I also 
perfer the looks of tatlin rendering my files, I use it as the (pre-)viewer and
not OpenSCAD.
