name: Build Debian package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3 # the repo is checkout out to /home/runner/work/tatlin/tatlin

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install debhelper
        sudo apt-get install dh-python
        sudo apt-get install python3-all
        sudo apt-get install python3-dev
        sudo apt-get install python3-setuptools
        sudo apt-get install python3-numpy
        sudo apt-get install python3-opengl
        sudo apt-get install python3-pil
        sudo apt-get install python3-six

    - name: Build DEB package
      run: |
        dpkg-buildpackage -b -rfakeroot -us -uc

    - name: Upload DEB package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: /home/runner/work/tatlin/*_all.deb

    # The GitHub CLI is pre-installed on GitHub-hosted runners.
    # https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
    - name: Create GitHub Release and Upload DEB package
      run: |
        TAG_NAME=${{ github.ref }}
        TAG_NAME=${TAG_NAME##refs/tags/}
        gh release create $TAG_NAME /home/runner/work/tatlin/*_all.deb --title "$TAG_NAME" --notes "Release of $TAG_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

