name: Run tests

# should run on every push to any branch except for tags
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # the repo is checkout out to /home/runner/work/tatlin/tatlin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Tatlin dependencies
        run: |
          # use prebuilt wxPython wheel to make the installation faster
          pip install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests
